owner: oxstreet # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Ox Street
    url: https://oxstreet.com
    maxResponseTime: 5000
  - name: User service
    url: https://api.oxstreet.com/users/v1/healthcheck
status-website: # Status website (optional)
  cname: /upptime # Custom domain CNAME
  name: Upptime # Status website title